# compose syntax version.
version: "3.6"

# services declaration.
services:
  # MySQL
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=main
      - MYSQL_USER=main
      - MYSQL_PASSWORD=main
    entrypoint:
        sh -c "
        echo 'CREATE DATABASE IF NOT EXISTS main; GRANT ALL PRIVILEGES ON main.* TO '\''main'\''@'\''%'\''; ' > /docker-entrypoint-initdb.d/init.sql;
        echo 'CREATE DATABASE IF NOT EXISTS test; GRANT ALL PRIVILEGES ON test.* TO '\''main'\''@'\''%'\''; ' >> /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
        "
    ports:
      - target: 3306
        published: 3306
  # Web Application
  web:
    image: ambientum/php:8.1-nginx
    volumes:
      - .:/var/www/app
      - dot-config:/home/ambientum/.config
      - dot-cache:/home/ambientum/.cache
      - dot-local:/home/ambientum/.local
      - dot-composer:/home/ambientum/.composer
    environment:
      - FRAMEWORK=laravel
      - XDEBUG_ENABLED=true
      - OPCACHE_MODE=normal
      - PHP_MEMORY_LIMIT=256M
    ports:
      - target: 8080
        published: 8080
      - target: 8083
        published: 8083
    links:
      - mysql
      - mailhog
  # Laravel Queue Worker
  queue:
    image: ambientum/php:8.1
    volumes:
      - .:/var/www/app
      - dot-config:/home/ambientum/.config
      - dot-cache:/home/ambientum/.cache
      - dot-local:/home/ambientum/.local
      - dot-composer:/home/ambientum/.composer
    command:
      - php
      - artisan
      - queue:work
    environment:
      - FRAMEWORK=laravel
      - XDEBUG_ENABLED=false
      - OPCACHE_MODE=disabled
      - PHP_MEMORY_LIMIT=256M
    links:
      - mysql
      - mailhog
  # MailHog
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - target: 1025
        published: 1025
      - target: 8025
        published: 8025

# volumes declaration.
volumes:
  # mysql-data
  mysql-data:
    driver: local
  # dot-config
  dot-config:
    driver: local
  # dot-cache
  dot-cache:
    driver: local
  # dot-local
  dot-local:
    driver: local
  # dot-composer
  dot-composer:
    driver: local
